---
title: "Solving Ordinary Differential Equations using an ODEnet"
subtitle: ""
author: "Lenin Rafael Riera Segura"
institute: "KAUST"
date: "`r format(Sys.time(), '%d-%m-%Y')`\n Based on the article on Neural ordinary differential equations by Chen, Rubanova, Bettencourt, and Duvenaud [Che+18] and the torchdiffeq repository [Che18]."
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      ratio: '16:9'
      slideNumberFormat: '%current%'
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      #countdown: 60000
      navigation:
        scroll: true # disable slide transitions by scrolling
    css: 
      - default
      - xaringan-themer.css
      - lenin.css
mathjax: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"
---
```{r, load_refs, include=FALSE, cache=FALSE}
library(RefManageR)
BibOptions(check.entries = FALSE,
           bib.style = "authoryear",
           cite.style = "alphabetic",
           style = "markdown",
           hyperlink = FALSE,
           dashed = FALSE)
myBib <- ReadBib("./ref.bib", check = FALSE)
```

```{r setup, echo = FALSE}
options(htmltools.dir.version = FALSE)
library(xaringanthemer)
style_mono_accent(base_color = "#005EB8")
htmltools::tagList(
  xaringanExtra::use_clipboard(
    button_text = "<i class=\"fa-solid fa-clipboard\" style=\"color: #00008B\"></i>",
    success_text = "<i class=\"fa fa-check\" style=\"color: #90BE6D\"></i>",
    error_text = "<i class=\"fa fa-times-circle\" style=\"color: #F94144\"></i>"
  ),
  rmarkdown::html_dependency_font_awesome()
)
knitr::opts_chunk$set(
  message = FALSE,    
  warning = FALSE,    
  echo = FALSE,        
  include = TRUE,     
  eval = TRUE,       
  cache = FALSE,       
  fig.align = "center",
  out.width = "90%",
  dpi = 300,
  error = TRUE,
  collapse = TRUE
)
```
